/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as tokens from "./tokens";
export type { tokens };
export type { DepositCertificate } from "./DepositCertificate";
export type { DepositVault } from "./DepositVault";
export type { SavingLogic } from "./SavingLogic";
export type { VaultManager } from "./VaultManager";
