/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Types {
  export type DepositStruct = {
    depositId: BigNumberish;
    owner: AddressLike;
    planId: BigNumberish;
    principal: BigNumberish;
    startAt: BigNumberish;
    maturityAt: BigNumberish;
    status: BigNumberish;
    aprBpsAtOpen: BigNumberish;
    penaltyBpsAtOpen: BigNumberish;
  };

  export type DepositStructOutput = [
    depositId: bigint,
    owner: string,
    planId: bigint,
    principal: bigint,
    startAt: bigint,
    maturityAt: bigint,
    status: bigint,
    aprBpsAtOpen: bigint,
    penaltyBpsAtOpen: bigint
  ] & {
    depositId: bigint;
    owner: string;
    planId: bigint;
    principal: bigint;
    startAt: bigint;
    maturityAt: bigint;
    status: bigint;
    aprBpsAtOpen: bigint;
    penaltyBpsAtOpen: bigint;
  };

  export type PlanStruct = {
    planId: BigNumberish;
    tenorDays: BigNumberish;
    aprBps: BigNumberish;
    minDeposit: BigNumberish;
    maxDeposit: BigNumberish;
    earlyWithdrawPenaltyBps: BigNumberish;
    enabled: boolean;
    createdAt: BigNumberish;
  };

  export type PlanStructOutput = [
    planId: bigint,
    tenorDays: bigint,
    aprBps: bigint,
    minDeposit: bigint,
    maxDeposit: bigint,
    earlyWithdrawPenaltyBps: bigint,
    enabled: boolean,
    createdAt: bigint
  ] & {
    planId: bigint;
    tenorDays: bigint;
    aprBps: bigint;
    minDeposit: bigint;
    maxDeposit: bigint;
    earlyWithdrawPenaltyBps: bigint;
    enabled: boolean;
    createdAt: bigint;
  };
}

export interface SavingCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approve"
      | "autoRenewDeposit"
      | "balanceOf"
      | "createPlan"
      | "deposits"
      | "earlyWithdraw"
      | "getApproved"
      | "getDeposit"
      | "getPlan"
      | "gracePeriod"
      | "isApprovedForAll"
      | "name"
      | "openDeposit"
      | "owner"
      | "ownerOf"
      | "plans"
      | "renewDeposit"
      | "renounceOwnership"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setGracePeriod"
      | "setVaultManager"
      | "supportsInterface"
      | "symbol"
      | "token"
      | "tokenURI"
      | "transferFrom"
      | "transferOwnership"
      | "updatePlan"
      | "vault"
      | "vaultManager"
      | "withdrawAtMaturity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "DepositOpened"
      | "OwnershipTransferred"
      | "PlanCreated"
      | "PlanUpdated"
      | "Renewed"
      | "Transfer"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "autoRenewDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createPlan",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deposits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "earlyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gracePeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "openDeposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "plans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "renewDeposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setGracePeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlan",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vaultManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAtMaturity",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "autoRenewDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createPlan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "earlyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gracePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renewDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGracePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVaultManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updatePlan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAtMaturity",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositOpenedEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    owner: AddressLike,
    planId: BigNumberish,
    principal: BigNumberish,
    maturityAt: BigNumberish,
    aprBpsAtOpen: BigNumberish
  ];
  export type OutputTuple = [
    depositId: bigint,
    owner: string,
    planId: bigint,
    principal: bigint,
    maturityAt: bigint,
    aprBpsAtOpen: bigint
  ];
  export interface OutputObject {
    depositId: bigint;
    owner: string;
    planId: bigint;
    principal: bigint;
    maturityAt: bigint;
    aprBpsAtOpen: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanCreatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    tenorDays: BigNumberish,
    aprBps: BigNumberish
  ];
  export type OutputTuple = [planId: bigint, tenorDays: bigint, aprBps: bigint];
  export interface OutputObject {
    planId: bigint;
    tenorDays: bigint;
    aprBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanUpdatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    tenorDays: BigNumberish,
    aprBps: BigNumberish,
    minDeposit: BigNumberish,
    maxDeposit: BigNumberish,
    earlyWithdrawPenaltyBps: BigNumberish,
    enabled: boolean
  ];
  export type OutputTuple = [
    planId: bigint,
    tenorDays: bigint,
    aprBps: bigint,
    minDeposit: bigint,
    maxDeposit: bigint,
    earlyWithdrawPenaltyBps: bigint,
    enabled: boolean
  ];
  export interface OutputObject {
    planId: bigint;
    tenorDays: bigint;
    aprBps: bigint;
    minDeposit: bigint;
    maxDeposit: bigint;
    earlyWithdrawPenaltyBps: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RenewedEvent {
  export type InputTuple = [
    oldDepositId: BigNumberish,
    newDepositId: BigNumberish,
    newPrincipal: BigNumberish,
    newPlanId: BigNumberish
  ];
  export type OutputTuple = [
    oldDepositId: bigint,
    newDepositId: bigint,
    newPrincipal: bigint,
    newPlanId: bigint
  ];
  export interface OutputObject {
    oldDepositId: bigint;
    newDepositId: bigint;
    newPrincipal: bigint;
    newPlanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    owner: AddressLike,
    principal: BigNumberish,
    interest: BigNumberish,
    isEarly: boolean
  ];
  export type OutputTuple = [
    depositId: bigint,
    owner: string,
    principal: bigint,
    interest: bigint,
    isEarly: boolean
  ];
  export interface OutputObject {
    depositId: bigint;
    owner: string;
    principal: bigint;
    interest: bigint;
    isEarly: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SavingCore extends BaseContract {
  connect(runner?: ContractRunner | null): SavingCore;
  waitForDeployment(): Promise<this>;

  interface: SavingCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  autoRenewDeposit: TypedContractMethod<
    [depositId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  createPlan: TypedContractMethod<
    [
      tenorDays: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  deposits: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        depositId: bigint;
        owner: string;
        planId: bigint;
        principal: bigint;
        startAt: bigint;
        maturityAt: bigint;
        status: bigint;
        aprBpsAtOpen: bigint;
        penaltyBpsAtOpen: bigint;
      }
    ],
    "view"
  >;

  earlyWithdraw: TypedContractMethod<
    [depositId: BigNumberish],
    [[bigint, bigint] & { principalAfterPenalty: bigint; penalty: bigint }],
    "nonpayable"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getDeposit: TypedContractMethod<
    [depositId: BigNumberish],
    [Types.DepositStructOutput],
    "view"
  >;

  getPlan: TypedContractMethod<
    [planId: BigNumberish],
    [Types.PlanStructOutput],
    "view"
  >;

  gracePeriod: TypedContractMethod<[], [bigint], "view">;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  openDeposit: TypedContractMethod<
    [planId: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  plans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        planId: bigint;
        tenorDays: bigint;
        aprBps: bigint;
        minDeposit: bigint;
        maxDeposit: bigint;
        earlyWithdrawPenaltyBps: bigint;
        enabled: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  renewDeposit: TypedContractMethod<
    [depositId: BigNumberish, newPlanId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setGracePeriod: TypedContractMethod<
    [newGracePeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVaultManager: TypedContractMethod<
    [newVaultManager: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  token: TypedContractMethod<[], [string], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePlan: TypedContractMethod<
    [
      planId: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;

  vault: TypedContractMethod<[], [string], "view">;

  vaultManager: TypedContractMethod<[], [string], "view">;

  withdrawAtMaturity: TypedContractMethod<
    [depositId: BigNumberish],
    [[bigint, bigint] & { principal: bigint; interest: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "autoRenewDeposit"
  ): TypedContractMethod<[depositId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPlan"
  ): TypedContractMethod<
    [
      tenorDays: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposits"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        depositId: bigint;
        owner: string;
        planId: bigint;
        principal: bigint;
        startAt: bigint;
        maturityAt: bigint;
        status: bigint;
        aprBpsAtOpen: bigint;
        penaltyBpsAtOpen: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "earlyWithdraw"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [[bigint, bigint] & { principalAfterPenalty: bigint; penalty: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getDeposit"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [Types.DepositStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlan"
  ): TypedContractMethod<
    [planId: BigNumberish],
    [Types.PlanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "gracePeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "openDeposit"
  ): TypedContractMethod<
    [planId: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "plans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        planId: bigint;
        tenorDays: bigint;
        aprBps: bigint;
        minDeposit: bigint;
        maxDeposit: bigint;
        earlyWithdrawPenaltyBps: bigint;
        enabled: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renewDeposit"
  ): TypedContractMethod<
    [depositId: BigNumberish, newPlanId: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGracePeriod"
  ): TypedContractMethod<[newGracePeriod: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVaultManager"
  ): TypedContractMethod<[newVaultManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePlan"
  ): TypedContractMethod<
    [
      planId: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vaultManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawAtMaturity"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [[bigint, bigint] & { principal: bigint; interest: bigint }],
    "nonpayable"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "DepositOpened"
  ): TypedContractEvent<
    DepositOpenedEvent.InputTuple,
    DepositOpenedEvent.OutputTuple,
    DepositOpenedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlanCreated"
  ): TypedContractEvent<
    PlanCreatedEvent.InputTuple,
    PlanCreatedEvent.OutputTuple,
    PlanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PlanUpdated"
  ): TypedContractEvent<
    PlanUpdatedEvent.InputTuple,
    PlanUpdatedEvent.OutputTuple,
    PlanUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Renewed"
  ): TypedContractEvent<
    RenewedEvent.InputTuple,
    RenewedEvent.OutputTuple,
    RenewedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "DepositOpened(uint256,address,uint256,uint256,uint256,uint16)": TypedContractEvent<
      DepositOpenedEvent.InputTuple,
      DepositOpenedEvent.OutputTuple,
      DepositOpenedEvent.OutputObject
    >;
    DepositOpened: TypedContractEvent<
      DepositOpenedEvent.InputTuple,
      DepositOpenedEvent.OutputTuple,
      DepositOpenedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlanCreated(uint256,uint32,uint16)": TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;
    PlanCreated: TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;

    "PlanUpdated(uint256,uint32,uint16,uint256,uint256,uint16,bool)": TypedContractEvent<
      PlanUpdatedEvent.InputTuple,
      PlanUpdatedEvent.OutputTuple,
      PlanUpdatedEvent.OutputObject
    >;
    PlanUpdated: TypedContractEvent<
      PlanUpdatedEvent.InputTuple,
      PlanUpdatedEvent.OutputTuple,
      PlanUpdatedEvent.OutputObject
    >;

    "Renewed(uint256,uint256,uint256,uint256)": TypedContractEvent<
      RenewedEvent.InputTuple,
      RenewedEvent.OutputTuple,
      RenewedEvent.OutputObject
    >;
    Renewed: TypedContractEvent<
      RenewedEvent.InputTuple,
      RenewedEvent.OutputTuple,
      RenewedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Withdrawn(uint256,address,uint256,uint256,bool)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
