/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Types {
  export type DepositCoreStruct = {
    depositId: BigNumberish;
    planId: BigNumberish;
    principal: BigNumberish;
    startAt: BigNumberish;
    maturityAt: BigNumberish;
    aprBpsAtOpen: BigNumberish;
    penaltyBpsAtOpen: BigNumberish;
    status: BigNumberish;
  };

  export type DepositCoreStructOutput = [
    depositId: bigint,
    planId: bigint,
    principal: bigint,
    startAt: bigint,
    maturityAt: bigint,
    aprBpsAtOpen: bigint,
    penaltyBpsAtOpen: bigint,
    status: bigint
  ] & {
    depositId: bigint;
    planId: bigint;
    principal: bigint;
    startAt: bigint;
    maturityAt: bigint;
    aprBpsAtOpen: bigint;
    penaltyBpsAtOpen: bigint;
    status: bigint;
  };

  export type PlanCoreStruct = {
    planId: BigNumberish;
    tenorSeconds: BigNumberish;
    aprBps: BigNumberish;
    minDeposit: BigNumberish;
    maxDeposit: BigNumberish;
    earlyWithdrawPenaltyBps: BigNumberish;
    isActive: boolean;
    createdAt: BigNumberish;
  };

  export type PlanCoreStructOutput = [
    planId: bigint,
    tenorSeconds: bigint,
    aprBps: bigint,
    minDeposit: bigint,
    maxDeposit: bigint,
    earlyWithdrawPenaltyBps: bigint,
    isActive: boolean,
    createdAt: bigint
  ] & {
    planId: bigint;
    tenorSeconds: bigint;
    aprBps: bigint;
    minDeposit: bigint;
    maxDeposit: bigint;
    earlyWithdrawPenaltyBps: bigint;
    isActive: boolean;
    createdAt: bigint;
  };
}

export interface SavingLogicInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "autoRenewDeposit"
      | "certificate"
      | "createPlan"
      | "depositVault"
      | "earlyWithdraw"
      | "getDepositCore"
      | "getPlan"
      | "gracePeriod"
      | "openDeposit"
      | "owner"
      | "plans"
      | "renewDeposit"
      | "renounceOwnership"
      | "setGracePeriod"
      | "setVaultManager"
      | "token"
      | "transferOwnership"
      | "updatePlan"
      | "vaultManager"
      | "withdrawAtMaturity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositOpened"
      | "OwnershipTransferred"
      | "PlanCreated"
      | "PlanUpdated"
      | "Renewed"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "autoRenewDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "certificate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPlan",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "earlyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositCore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gracePeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openDeposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "plans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "renewDeposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGracePeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlan",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAtMaturity",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "autoRenewDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "earlyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gracePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renewDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGracePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVaultManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updatePlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAtMaturity",
    data: BytesLike
  ): Result;
}

export namespace DepositOpenedEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    owner: AddressLike,
    planId: BigNumberish,
    principal: BigNumberish,
    maturityAt: BigNumberish,
    aprBps: BigNumberish
  ];
  export type OutputTuple = [
    depositId: bigint,
    owner: string,
    planId: bigint,
    principal: bigint,
    maturityAt: bigint,
    aprBps: bigint
  ];
  export interface OutputObject {
    depositId: bigint;
    owner: string;
    planId: bigint;
    principal: bigint;
    maturityAt: bigint;
    aprBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanCreatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    tenorSeconds: BigNumberish,
    aprBps: BigNumberish
  ];
  export type OutputTuple = [
    planId: bigint,
    tenorSeconds: bigint,
    aprBps: bigint
  ];
  export interface OutputObject {
    planId: bigint;
    tenorSeconds: bigint;
    aprBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanUpdatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    aprBps: BigNumberish,
    minDeposit: BigNumberish,
    maxDeposit: BigNumberish,
    penaltyBps: BigNumberish,
    isActive: boolean
  ];
  export type OutputTuple = [
    planId: bigint,
    aprBps: bigint,
    minDeposit: bigint,
    maxDeposit: bigint,
    penaltyBps: bigint,
    isActive: boolean
  ];
  export interface OutputObject {
    planId: bigint;
    aprBps: bigint;
    minDeposit: bigint;
    maxDeposit: bigint;
    penaltyBps: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RenewedEvent {
  export type InputTuple = [
    oldDepositId: BigNumberish,
    newDepositId: BigNumberish,
    newPlanId: BigNumberish,
    newPrincipal: BigNumberish,
    isAuto: boolean
  ];
  export type OutputTuple = [
    oldDepositId: bigint,
    newDepositId: bigint,
    newPlanId: bigint,
    newPrincipal: bigint,
    isAuto: boolean
  ];
  export interface OutputObject {
    oldDepositId: bigint;
    newDepositId: bigint;
    newPlanId: bigint;
    newPrincipal: bigint;
    isAuto: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    owner: AddressLike,
    principal: BigNumberish,
    interest: BigNumberish,
    isEarly: boolean
  ];
  export type OutputTuple = [
    depositId: bigint,
    owner: string,
    principal: bigint,
    interest: bigint,
    isEarly: boolean
  ];
  export interface OutputObject {
    depositId: bigint;
    owner: string;
    principal: bigint;
    interest: bigint;
    isEarly: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SavingLogic extends BaseContract {
  connect(runner?: ContractRunner | null): SavingLogic;
  waitForDeployment(): Promise<this>;

  interface: SavingLogicInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  autoRenewDeposit: TypedContractMethod<
    [oldDepositId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  certificate: TypedContractMethod<[], [string], "view">;

  createPlan: TypedContractMethod<
    [
      tenorSeconds: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  depositVault: TypedContractMethod<[], [string], "view">;

  earlyWithdraw: TypedContractMethod<
    [depositId: BigNumberish],
    [[bigint, bigint] & { principalAfterPenalty: bigint; penalty: bigint }],
    "nonpayable"
  >;

  getDepositCore: TypedContractMethod<
    [depositId: BigNumberish],
    [Types.DepositCoreStructOutput],
    "view"
  >;

  getPlan: TypedContractMethod<
    [planId: BigNumberish],
    [Types.PlanCoreStructOutput],
    "view"
  >;

  gracePeriod: TypedContractMethod<[], [bigint], "view">;

  openDeposit: TypedContractMethod<
    [planId: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  plans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        planId: bigint;
        tenorSeconds: bigint;
        aprBps: bigint;
        minDeposit: bigint;
        maxDeposit: bigint;
        earlyWithdrawPenaltyBps: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  renewDeposit: TypedContractMethod<
    [oldDepositId: BigNumberish, newPlanId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setGracePeriod: TypedContractMethod<
    [newGracePeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVaultManager: TypedContractMethod<
    [newVaultManager: AddressLike],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePlan: TypedContractMethod<
    [
      planId: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish,
      isActive: boolean
    ],
    [void],
    "nonpayable"
  >;

  vaultManager: TypedContractMethod<[], [string], "view">;

  withdrawAtMaturity: TypedContractMethod<
    [depositId: BigNumberish],
    [[bigint, bigint] & { principal: bigint; interest: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "autoRenewDeposit"
  ): TypedContractMethod<[oldDepositId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "certificate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createPlan"
  ): TypedContractMethod<
    [
      tenorSeconds: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "earlyWithdraw"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [[bigint, bigint] & { principalAfterPenalty: bigint; penalty: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDepositCore"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [Types.DepositCoreStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlan"
  ): TypedContractMethod<
    [planId: BigNumberish],
    [Types.PlanCoreStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "gracePeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openDeposit"
  ): TypedContractMethod<
    [planId: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "plans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        planId: bigint;
        tenorSeconds: bigint;
        aprBps: bigint;
        minDeposit: bigint;
        maxDeposit: bigint;
        earlyWithdrawPenaltyBps: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renewDeposit"
  ): TypedContractMethod<
    [oldDepositId: BigNumberish, newPlanId: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGracePeriod"
  ): TypedContractMethod<[newGracePeriod: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVaultManager"
  ): TypedContractMethod<[newVaultManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePlan"
  ): TypedContractMethod<
    [
      planId: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish,
      isActive: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaultManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawAtMaturity"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [[bigint, bigint] & { principal: bigint; interest: bigint }],
    "nonpayable"
  >;

  getEvent(
    key: "DepositOpened"
  ): TypedContractEvent<
    DepositOpenedEvent.InputTuple,
    DepositOpenedEvent.OutputTuple,
    DepositOpenedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlanCreated"
  ): TypedContractEvent<
    PlanCreatedEvent.InputTuple,
    PlanCreatedEvent.OutputTuple,
    PlanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PlanUpdated"
  ): TypedContractEvent<
    PlanUpdatedEvent.InputTuple,
    PlanUpdatedEvent.OutputTuple,
    PlanUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Renewed"
  ): TypedContractEvent<
    RenewedEvent.InputTuple,
    RenewedEvent.OutputTuple,
    RenewedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "DepositOpened(uint256,address,uint256,uint256,uint256,uint16)": TypedContractEvent<
      DepositOpenedEvent.InputTuple,
      DepositOpenedEvent.OutputTuple,
      DepositOpenedEvent.OutputObject
    >;
    DepositOpened: TypedContractEvent<
      DepositOpenedEvent.InputTuple,
      DepositOpenedEvent.OutputTuple,
      DepositOpenedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlanCreated(uint256,uint32,uint16)": TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;
    PlanCreated: TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;

    "PlanUpdated(uint256,uint16,uint256,uint256,uint16,bool)": TypedContractEvent<
      PlanUpdatedEvent.InputTuple,
      PlanUpdatedEvent.OutputTuple,
      PlanUpdatedEvent.OutputObject
    >;
    PlanUpdated: TypedContractEvent<
      PlanUpdatedEvent.InputTuple,
      PlanUpdatedEvent.OutputTuple,
      PlanUpdatedEvent.OutputObject
    >;

    "Renewed(uint256,uint256,uint256,uint256,bool)": TypedContractEvent<
      RenewedEvent.InputTuple,
      RenewedEvent.OutputTuple,
      RenewedEvent.OutputObject
    >;
    Renewed: TypedContractEvent<
      RenewedEvent.InputTuple,
      RenewedEvent.OutputTuple,
      RenewedEvent.OutputObject
    >;

    "Withdrawn(uint256,address,uint256,uint256,bool)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
