/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Types {
  export type DepositCoreStruct = {
    depositId: BigNumberish;
    planId: BigNumberish;
    principal: BigNumberish;
    startAt: BigNumberish;
    maturityAt: BigNumberish;
    aprBpsAtOpen: BigNumberish;
    penaltyBpsAtOpen: BigNumberish;
    status: BigNumberish;
  };

  export type DepositCoreStructOutput = [
    depositId: bigint,
    planId: bigint,
    principal: bigint,
    startAt: bigint,
    maturityAt: bigint,
    aprBpsAtOpen: bigint,
    penaltyBpsAtOpen: bigint,
    status: bigint
  ] & {
    depositId: bigint;
    planId: bigint;
    principal: bigint;
    startAt: bigint;
    maturityAt: bigint;
    aprBpsAtOpen: bigint;
    penaltyBpsAtOpen: bigint;
    status: bigint;
  };
}

export interface IDepositCertificateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "exists"
      | "getDepositCore"
      | "mint"
      | "savingLogic"
      | "setBaseURI"
      | "setSavingLogic"
      | "updateStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BaseURIUpdated"
      | "CertificateMinted"
      | "DepositStatusUpdated"
      | "SavingLogicUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "exists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositCore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, BigNumberish, Types.DepositCoreStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "savingLogic",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setBaseURI", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setSavingLogic",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "exists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDepositCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "savingLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBaseURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSavingLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;
}

export namespace BaseURIUpdatedEvent {
  export type InputTuple = [newBaseURI: string];
  export type OutputTuple = [newBaseURI: string];
  export interface OutputObject {
    newBaseURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateMintedEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    owner: AddressLike,
    planId: BigNumberish
  ];
  export type OutputTuple = [depositId: bigint, owner: string, planId: bigint];
  export interface OutputObject {
    depositId: bigint;
    owner: string;
    planId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositStatusUpdatedEvent {
  export type InputTuple = [depositId: BigNumberish, newStatus: BigNumberish];
  export type OutputTuple = [depositId: bigint, newStatus: bigint];
  export interface OutputObject {
    depositId: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SavingLogicUpdatedEvent {
  export type InputTuple = [oldLogic: AddressLike, newLogic: AddressLike];
  export type OutputTuple = [oldLogic: string, newLogic: string];
  export interface OutputObject {
    oldLogic: string;
    newLogic: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDepositCertificate extends BaseContract {
  connect(runner?: ContractRunner | null): IDepositCertificate;
  waitForDeployment(): Promise<this>;

  interface: IDepositCertificateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  exists: TypedContractMethod<[depositId: BigNumberish], [boolean], "view">;

  getDepositCore: TypedContractMethod<
    [depositId: BigNumberish],
    [Types.DepositCoreStructOutput],
    "view"
  >;

  mint: TypedContractMethod<
    [
      to: AddressLike,
      depositId: BigNumberish,
      depositCore: Types.DepositCoreStruct
    ],
    [void],
    "nonpayable"
  >;

  savingLogic: TypedContractMethod<[], [string], "view">;

  setBaseURI: TypedContractMethod<[newBaseURI: string], [void], "nonpayable">;

  setSavingLogic: TypedContractMethod<
    [newLogic: AddressLike],
    [void],
    "nonpayable"
  >;

  updateStatus: TypedContractMethod<
    [depositId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "exists"
  ): TypedContractMethod<[depositId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getDepositCore"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [Types.DepositCoreStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [
      to: AddressLike,
      depositId: BigNumberish,
      depositCore: Types.DepositCoreStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "savingLogic"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setBaseURI"
  ): TypedContractMethod<[newBaseURI: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSavingLogic"
  ): TypedContractMethod<[newLogic: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateStatus"
  ): TypedContractMethod<
    [depositId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BaseURIUpdated"
  ): TypedContractEvent<
    BaseURIUpdatedEvent.InputTuple,
    BaseURIUpdatedEvent.OutputTuple,
    BaseURIUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateMinted"
  ): TypedContractEvent<
    CertificateMintedEvent.InputTuple,
    CertificateMintedEvent.OutputTuple,
    CertificateMintedEvent.OutputObject
  >;
  getEvent(
    key: "DepositStatusUpdated"
  ): TypedContractEvent<
    DepositStatusUpdatedEvent.InputTuple,
    DepositStatusUpdatedEvent.OutputTuple,
    DepositStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SavingLogicUpdated"
  ): TypedContractEvent<
    SavingLogicUpdatedEvent.InputTuple,
    SavingLogicUpdatedEvent.OutputTuple,
    SavingLogicUpdatedEvent.OutputObject
  >;

  filters: {
    "BaseURIUpdated(string)": TypedContractEvent<
      BaseURIUpdatedEvent.InputTuple,
      BaseURIUpdatedEvent.OutputTuple,
      BaseURIUpdatedEvent.OutputObject
    >;
    BaseURIUpdated: TypedContractEvent<
      BaseURIUpdatedEvent.InputTuple,
      BaseURIUpdatedEvent.OutputTuple,
      BaseURIUpdatedEvent.OutputObject
    >;

    "CertificateMinted(uint256,address,uint256)": TypedContractEvent<
      CertificateMintedEvent.InputTuple,
      CertificateMintedEvent.OutputTuple,
      CertificateMintedEvent.OutputObject
    >;
    CertificateMinted: TypedContractEvent<
      CertificateMintedEvent.InputTuple,
      CertificateMintedEvent.OutputTuple,
      CertificateMintedEvent.OutputObject
    >;

    "DepositStatusUpdated(uint256,uint8)": TypedContractEvent<
      DepositStatusUpdatedEvent.InputTuple,
      DepositStatusUpdatedEvent.OutputTuple,
      DepositStatusUpdatedEvent.OutputObject
    >;
    DepositStatusUpdated: TypedContractEvent<
      DepositStatusUpdatedEvent.InputTuple,
      DepositStatusUpdatedEvent.OutputTuple,
      DepositStatusUpdatedEvent.OutputObject
    >;

    "SavingLogicUpdated(address,address)": TypedContractEvent<
      SavingLogicUpdatedEvent.InputTuple,
      SavingLogicUpdatedEvent.OutputTuple,
      SavingLogicUpdatedEvent.OutputObject
    >;
    SavingLogicUpdated: TypedContractEvent<
      SavingLogicUpdatedEvent.InputTuple,
      SavingLogicUpdatedEvent.OutputTuple,
      SavingLogicUpdatedEvent.OutputObject
    >;
  };
}
