/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDepositCertificate } from "./IDepositCertificate";
export type { ISavingCore } from "./ISavingCore";
export type { ISavingLogic } from "./ISavingLogic";
export type { IVaultManager } from "./IVaultManager";
