/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Types {
  export type DepositStruct = {
    depositId: BigNumberish;
    owner: AddressLike;
    planId: BigNumberish;
    principal: BigNumberish;
    startAt: BigNumberish;
    maturityAt: BigNumberish;
    status: BigNumberish;
    aprBpsAtOpen: BigNumberish;
    penaltyBpsAtOpen: BigNumberish;
  };

  export type DepositStructOutput = [
    depositId: bigint,
    owner: string,
    planId: bigint,
    principal: bigint,
    startAt: bigint,
    maturityAt: bigint,
    status: bigint,
    aprBpsAtOpen: bigint,
    penaltyBpsAtOpen: bigint
  ] & {
    depositId: bigint;
    owner: string;
    planId: bigint;
    principal: bigint;
    startAt: bigint;
    maturityAt: bigint;
    status: bigint;
    aprBpsAtOpen: bigint;
    penaltyBpsAtOpen: bigint;
  };

  export type PlanStruct = {
    planId: BigNumberish;
    tenorDays: BigNumberish;
    aprBps: BigNumberish;
    minDeposit: BigNumberish;
    maxDeposit: BigNumberish;
    earlyWithdrawPenaltyBps: BigNumberish;
    enabled: boolean;
    createdAt: BigNumberish;
  };

  export type PlanStructOutput = [
    planId: bigint,
    tenorDays: bigint,
    aprBps: bigint,
    minDeposit: bigint,
    maxDeposit: bigint,
    earlyWithdrawPenaltyBps: bigint,
    enabled: boolean,
    createdAt: bigint
  ] & {
    planId: bigint;
    tenorDays: bigint;
    aprBps: bigint;
    minDeposit: bigint;
    maxDeposit: bigint;
    earlyWithdrawPenaltyBps: bigint;
    enabled: boolean;
    createdAt: bigint;
  };
}

export interface ISavingCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "autoRenewDeposit"
      | "createPlan"
      | "earlyWithdraw"
      | "getDeposit"
      | "getPlan"
      | "gracePeriod"
      | "openDeposit"
      | "renewDeposit"
      | "token"
      | "updatePlan"
      | "vault"
      | "withdrawAtMaturity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositOpened"
      | "PlanCreated"
      | "PlanUpdated"
      | "Renewed"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "autoRenewDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPlan",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "earlyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gracePeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openDeposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renewDeposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updatePlan",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawAtMaturity",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "autoRenewDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "earlyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gracePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renewDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updatePlan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAtMaturity",
    data: BytesLike
  ): Result;
}

export namespace DepositOpenedEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    owner: AddressLike,
    planId: BigNumberish,
    principal: BigNumberish,
    maturityAt: BigNumberish,
    aprBpsAtOpen: BigNumberish
  ];
  export type OutputTuple = [
    depositId: bigint,
    owner: string,
    planId: bigint,
    principal: bigint,
    maturityAt: bigint,
    aprBpsAtOpen: bigint
  ];
  export interface OutputObject {
    depositId: bigint;
    owner: string;
    planId: bigint;
    principal: bigint;
    maturityAt: bigint;
    aprBpsAtOpen: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanCreatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    tenorDays: BigNumberish,
    aprBps: BigNumberish
  ];
  export type OutputTuple = [planId: bigint, tenorDays: bigint, aprBps: bigint];
  export interface OutputObject {
    planId: bigint;
    tenorDays: bigint;
    aprBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanUpdatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    tenorDays: BigNumberish,
    aprBps: BigNumberish,
    minDeposit: BigNumberish,
    maxDeposit: BigNumberish,
    earlyWithdrawPenaltyBps: BigNumberish,
    enabled: boolean
  ];
  export type OutputTuple = [
    planId: bigint,
    tenorDays: bigint,
    aprBps: bigint,
    minDeposit: bigint,
    maxDeposit: bigint,
    earlyWithdrawPenaltyBps: bigint,
    enabled: boolean
  ];
  export interface OutputObject {
    planId: bigint;
    tenorDays: bigint;
    aprBps: bigint;
    minDeposit: bigint;
    maxDeposit: bigint;
    earlyWithdrawPenaltyBps: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RenewedEvent {
  export type InputTuple = [
    oldDepositId: BigNumberish,
    newDepositId: BigNumberish,
    newPrincipal: BigNumberish,
    newPlanId: BigNumberish
  ];
  export type OutputTuple = [
    oldDepositId: bigint,
    newDepositId: bigint,
    newPrincipal: bigint,
    newPlanId: bigint
  ];
  export interface OutputObject {
    oldDepositId: bigint;
    newDepositId: bigint;
    newPrincipal: bigint;
    newPlanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    owner: AddressLike,
    principal: BigNumberish,
    interest: BigNumberish,
    isEarly: boolean
  ];
  export type OutputTuple = [
    depositId: bigint,
    owner: string,
    principal: bigint,
    interest: bigint,
    isEarly: boolean
  ];
  export interface OutputObject {
    depositId: bigint;
    owner: string;
    principal: bigint;
    interest: bigint;
    isEarly: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISavingCore extends BaseContract {
  connect(runner?: ContractRunner | null): ISavingCore;
  waitForDeployment(): Promise<this>;

  interface: ISavingCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  autoRenewDeposit: TypedContractMethod<
    [depositId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  createPlan: TypedContractMethod<
    [
      tenorDays: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  earlyWithdraw: TypedContractMethod<
    [depositId: BigNumberish],
    [[bigint, bigint] & { principalAfterPenalty: bigint; penalty: bigint }],
    "nonpayable"
  >;

  getDeposit: TypedContractMethod<
    [depositId: BigNumberish],
    [Types.DepositStructOutput],
    "view"
  >;

  getPlan: TypedContractMethod<
    [planId: BigNumberish],
    [Types.PlanStructOutput],
    "view"
  >;

  gracePeriod: TypedContractMethod<[], [bigint], "view">;

  openDeposit: TypedContractMethod<
    [planId: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renewDeposit: TypedContractMethod<
    [depositId: BigNumberish, newPlanId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  updatePlan: TypedContractMethod<
    [
      planId: BigNumberish,
      tenorDays: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;

  vault: TypedContractMethod<[], [string], "view">;

  withdrawAtMaturity: TypedContractMethod<
    [depositId: BigNumberish],
    [[bigint, bigint] & { principal: bigint; interest: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "autoRenewDeposit"
  ): TypedContractMethod<[depositId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "createPlan"
  ): TypedContractMethod<
    [
      tenorDays: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "earlyWithdraw"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [[bigint, bigint] & { principalAfterPenalty: bigint; penalty: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDeposit"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [Types.DepositStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlan"
  ): TypedContractMethod<
    [planId: BigNumberish],
    [Types.PlanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "gracePeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openDeposit"
  ): TypedContractMethod<
    [planId: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renewDeposit"
  ): TypedContractMethod<
    [depositId: BigNumberish, newPlanId: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updatePlan"
  ): TypedContractMethod<
    [
      planId: BigNumberish,
      tenorDays: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawAtMaturity"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [[bigint, bigint] & { principal: bigint; interest: bigint }],
    "nonpayable"
  >;

  getEvent(
    key: "DepositOpened"
  ): TypedContractEvent<
    DepositOpenedEvent.InputTuple,
    DepositOpenedEvent.OutputTuple,
    DepositOpenedEvent.OutputObject
  >;
  getEvent(
    key: "PlanCreated"
  ): TypedContractEvent<
    PlanCreatedEvent.InputTuple,
    PlanCreatedEvent.OutputTuple,
    PlanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PlanUpdated"
  ): TypedContractEvent<
    PlanUpdatedEvent.InputTuple,
    PlanUpdatedEvent.OutputTuple,
    PlanUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Renewed"
  ): TypedContractEvent<
    RenewedEvent.InputTuple,
    RenewedEvent.OutputTuple,
    RenewedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "DepositOpened(uint256,address,uint256,uint256,uint256,uint16)": TypedContractEvent<
      DepositOpenedEvent.InputTuple,
      DepositOpenedEvent.OutputTuple,
      DepositOpenedEvent.OutputObject
    >;
    DepositOpened: TypedContractEvent<
      DepositOpenedEvent.InputTuple,
      DepositOpenedEvent.OutputTuple,
      DepositOpenedEvent.OutputObject
    >;

    "PlanCreated(uint256,uint32,uint16)": TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;
    PlanCreated: TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;

    "PlanUpdated(uint256,uint32,uint16,uint256,uint256,uint16,bool)": TypedContractEvent<
      PlanUpdatedEvent.InputTuple,
      PlanUpdatedEvent.OutputTuple,
      PlanUpdatedEvent.OutputObject
    >;
    PlanUpdated: TypedContractEvent<
      PlanUpdatedEvent.InputTuple,
      PlanUpdatedEvent.OutputTuple,
      PlanUpdatedEvent.OutputObject
    >;

    "Renewed(uint256,uint256,uint256,uint256)": TypedContractEvent<
      RenewedEvent.InputTuple,
      RenewedEvent.OutputTuple,
      RenewedEvent.OutputObject
    >;
    Renewed: TypedContractEvent<
      RenewedEvent.InputTuple,
      RenewedEvent.OutputTuple,
      RenewedEvent.OutputObject
    >;

    "Withdrawn(uint256,address,uint256,uint256,bool)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
